### ISSUE TITLE
Discussion: making currying more Laravel friendly

### ISSUE THREAD

**Issue by nunomaduro** [nunomaduro/curryable#1]
Today, this library is not stable yet. This means that we are free that change the public API, and the internals.  Wondering how can we make currying more Laravel friendly, a macro on collections? Something else? Let's discuss this.

One of the reasons why nobody adopts current functional programming libraries in PHP is that they completely forget the current ecosystem, making their adoption with Laravel and Symfony more difficult.

As example, today we have a [Service Provider](https://github.com/nunomaduro/curryable/blob/3d6bd3ad8333207f9ddff4d624bb348193c87f36/src/Adapters/Laravel/CurryableServiceProvider.php#L20) that injects a macro on Laravel models allowing to create stuff like this:

```php
Route::get('user/{id}', User::curry()->find());

// Translates to:
Route::get('user/{id}', function () {
    return User::curry()->find(...func_get_args());
});
```

The goal of curry is really creating a closure out of the given expression. As example:

```php
curry($object)->foo();

// translates too:
function () {
    return $object->foo(...func_get_args());
})
```

We can also give the arguments of the function

```php
curry($object)->foo($first);

// translates too:
function () use ($first) {
    return $object->foo($first, ...func_get_args());
})
```

More examples here: https://github.com/nunomaduro/curryable#on-macros.

Please add comments in this issue with your ideas. There is tons of potential here. ❤️

**Comment by NastuzziSamy** [comment]
Hi, I really like the idea ! 

Maybe adding a Facade ? Bootstrap functions tend to be removed in favor of facades. 

```php 
// Closure finding a user. 
Currry::find(User::class);

// Closure for calling foo on object. 
Curry::foo($object);

// Closure with a dynamic method name. 
Curry::call($whatever, $methodName);
// Use the first argument as the method name. 
Curry::call($whatever);

// Closure with a dynamic method name. 
Curry::callStatic($whatever, $methodName);
// Use the first argument as the method name. 
Curry::callStatic($whatever);

// Of course, you can pass args: 
Curry::whatever($wathever, ...$args);
Curry::call($wathever, $nullableMethodName, ...$args);
Curry::callStatic($wathever, $nullableMethodName, ...$args);
```

I think that this approach is simplier, more consistent and elegant. 

I can make a PR if you like the idea! 

And thanks again for having thinking about it

**Comment by nunomaduro** [comment]
Let's keep this on hold for some days.
